apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shahlaa

resources:
  - server/deployment.yml
  - server/secret.yml
  - server/service.yml
  # - admin/deployment.yml
  # - admin/secret.yml
  # - admin/service.yml
  
images:
  - name: store-server
    newName: mohammaddocker/medusa-shahlaa-server
    newTag: 0.1.0
  # - name: store-admin
  #   newName: mohammaddocker/medusa-shahlaa-admin
  #   newTag: 0.0.8