services:
  database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "medusa"
      POSTGRES_PASSWORD: "medusa"
      POSTGRES_DB: "medusa"
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=medusa"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  cache:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  store:
    image: store:0.0.8
    environment:
      - DATABASE_TYPE=postgres
      - MEDUSA_ADMIN_ONBOARDING_TYPE=nextjs
      - STORE_CORS=http://localhost:8000,http://localhost:7001
      - MEDUSA_ADMIN_ONBOARDING_NEXTJS_DIRECTORY=storefront
      - LOCALE=fr
      - STRIPE_API_KEY=sk_test_51PlsgFGwyU8iYL2FQhiyZgVgd4lNqJdz7Fy9g8ugv7b6mCUuKlyi8owfukUoj5VXqUyhNp2sbtTXePHjvaD2qOLQ005PZ72EhC
      - DATABASE_URL=postgres://medusa:medusa@database:5432/medusa
      - REDIS_URL=redis://cache:6379
      - JWT_SECRET=something
      - COOKIE_SECRET=something

  admin:
    image: admin
    environment:
      - MEDUSA_BACKEND_URL=http://store:3000
    ports:
      - "3000:80"

