services:
  database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "medusa"
      POSTGRES_PASSWORD: "medusa"
      POSTGRES_DB: "medusa"
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=medusa"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  cache:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  server:


