apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: shalhaa-admin-secret
  annotations:
    argocd.argoproj.io/synchronization: Exclude
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.vault.svc.cluster.local:8080/api

  authentication:
    # Make sure to only have 1 authentication method defined, serviceToken/universalAuth.
    # If you have multiple authentication methods defined, it may cause issues.

    # Universal Auth
    universalAuth:
      secretsScope:
        projectSlug: e-commerce-shahlaa-fo65
        envSlug: staging # "dev", "staging", "prod", etc..
        secretsPath: "/admin"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: vault

  managedSecretReference:
    secretName: managed-secret-admin
    secretNamespace: shahlaa
    creationPolicy: "Orphan" ## Owner | Orphan
