apiVersion: apps/v1
kind: Deployment
metadata:
  name: medusa-shahlaa-server
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: medusa-shahlaa-server
  template:
    metadata:
      labels:
        app: medusa-shahlaa-server
    spec:
      containers:
        - image: store-server
          name: medusa-shahlaa-server
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 600m
              memory: 1000Mi
          envFrom:
            - secretRef:
                name: managed-secret-server